# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackaTUM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hackaTUM
  pod 'XCGLogger', '~> 7.0.0'
  pod 'ARCoreLocation', '~> 0.1.9'
  pod 'EMAlertController'
  
end
